Initialisation script for database and githooks.  The initialisation script for the database was still in progress and it needed to be completed so the system can include 5 valid games with 3 test accounts and 3 reviews per account. Githooks didn't exactly improve code quality.  Initialisation script for the database was finished for all modules, accounts.js, games.js and reviews.js. Each module required a new function where it checks if their table in the database was empty. If so the function for games.js and reviews.js will read in a SQL insert command from text files that were added and stored in a new directory called DBinit and insert data into the tables that were created by the constructor. The function in the accounts.js has an insert command stored as a const variable with another function to encrypt the passwords with different hashes, as the test accounts have the same password. Index.js was also modified to call the init functions when the server starts up.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -33,15 +33,24 @@ then
 	exit 1
 fi
 
-#eslint=`./node_modules/.bin/eslint .`
-#echo "$(./node_modules/.bin/eslint .)"
-#if [[ $($eslint -A) ]]
-#then
-#	echo "You don't have problems in code."
-	#exit 1
-#else
-#	echo "You have problems in code"
-#fi
+echo && echo -e "\033[1;33mCode Quality Checks.\033[0m"
+
+# if eslint returns a warning/error the githook will exit with a non zero status
+echo && echo "Running lint checks..."
+./node_modules/.bin/eslint . || exit 1
+# informs user in green text that code has passed linting
+echo -e "\033[0;32mNo linting warnings/errors.\033[0m"
+
+# if unit testing fails githook will exit with a non zero status, npm test already
+# tells the user what has failed
+echo && echo "Running unit tests..."
+npm run test || exit 1
+
+# see above etc
+echo && echo "Running JSDocs tool..."
+npm run jsdoc
+# informs user in green text that JSDoc has been generated
+echo -e "\033[0;32mJSDocs successfully generated. \033[0m"
 
 # checks if the user is trying to merge a branch into the master branch
 branch="$(git rev-parse --abbrev-ref HEAD)"
